#!/usr/bin/perl
# Extract the DTC (traction control) data from an M Race Calibration .bmwrc25 file (XML)
# into a JS dataset for the prototype:  perl tools/bmwrc25-to-js.pl file.bmwrc25 > js/dataset.js
#
#   slip_target_1..15        map: x = lean angle [deg], y = mu_x, values = slip target [%]
#   slip_target_alloc_<mode> map: x = sector 1..15, y = gear 1..6, values = map id
#   slip_shift_fak / _ofst   map: x = user level -7..7, y = sector 1..15
#   torque_reduction_method  characteristic
#   traction_control_mode    map: x = sector, y = vehicle mode 1..4
use strict;
use warnings;

my $file = shift or die "usage: $0 file.bmwrc25\n";
open my $fh, '<', $file or die "$file: $!\n";
local $/;
my $xml = <$fh>;
close $fh;

sub block {
  my ($tag, $name) = @_;
  $xml =~ m{<$tag name="\Q$name\E">(.*?)</$tag>}s or die "missing $tag $name\n";
  return $1;
}
sub nums { return [ map { 0 + $_ } split /,/, $_[0] ] }
sub map_of {
  my $b = block('map', $_[0]);
  my ($x) = $b =~ m{<suppoints_x[^>]*>([^<]*)</suppoints_x>};
  my ($y) = $b =~ m{<suppoints_y[^>]*>([^<]*)</suppoints_y>};
  my @rows;
  while ($b =~ m{<y(\d+)>([^<]*)</y\1>}g) { $rows[$1] = nums($2) }
  return { x => nums($x), y => nums($y), rows => \@rows };
}
sub r { my ($v, $d) = @_; my $f = 10 ** $d; return int($v * $f + ($v < 0 ? -0.5 : 0.5)) / $f }
sub js { my $a = shift; return '[' . join(',', map { ref $_ ? js($_) : $_ } @$a) . ']' }
sub str { my $s = shift // ''; $s =~ s/(["\\])/\\$1/g; $s =~ s/[\r\n]+/ /g; return "\"$s\"" }

# Slip target maps: the prototype keeps the lean axis in descending order (70 -> 0 on screen).
my (@targets, $mu);
for my $i (1 .. 15) {
  my $m = map_of("slip_target_$i");
  $mu ||= [ map { r($_, 2) } @{ $m->{y} } ];
  my @lean = reverse @{ $m->{x} };
  my @rows = map { [ reverse map { r($_, 1) } @$_ ] } @{ $m->{rows} };
  push @targets, "{ id: $i, lean: " . js(\@lean) . ", rows: " . js(\@rows) . " }";
}

# Allocation per vehicle mode: one map per gear (sector 1; the tool warns if sectors differ).
my %alloc;
my @notes;
for my $mode (qw(rain int dry1 dry2)) {
  my $m = map_of("slip_target_alloc_$mode");
  my @per_gear;
  for my $g (0 .. $#{ $m->{rows} }) {
    my @s = @{ $m->{rows}[$g] };
    push @per_gear, $s[0];
    push @notes, "alloc $mode gear " . ($g + 1) . " differs per sector" if grep { $_ != $s[0] } @s;
  }
  $alloc{$mode} = \@per_gear;
}

# User offset / factor per user level (sector 1).
my $fak = map_of('slip_shift_fak');
my $ofs = map_of('slip_shift_ofst');
my @fac = map { r($_, 2) } @{ $fak->{rows}[0] };
my @off = map { r($_, 1) } @{ $ofs->{rows}[0] };
my $facStep = r(($fac[7] - $fac[8]), 3);
my $offStep = r(($off[7] - $off[8]), 2);

my ($red) = block('characteristic', 'torque_reduction_method') =~ m{<value>([^<]*)</value>};
my $tcm = map_of('traction_control_mode');
my @dtc = map { $_->[0] } @{ $tcm->{rows} };
my ($desc) = $xml =~ m{<desc>([^<]*)</desc>};
my ($date) = $xml =~ m{<date>([^<]*)</date>};

print "// Generated by tools/bmwrc25-to-js.pl from $file\n";
print "// $_\n" for @notes;
print "window.MRCK_DATASET = {\n";
print "  source: " . str($desc) . ", date: " . str($date) . ",\n";
print "  MU_ROWS: " . js($mu) . ",\n";
print "  targets: [\n    " . join(",\n    ", @targets) . ",\n  ],\n";
print "  allocation: { Rain: " . js($alloc{rain}) . ", Int: " . js($alloc{int}) .
      ", Dry1: " . js($alloc{dry1}) . ", Dry2: " . js($alloc{dry2}) . " },\n";
print "  userShift: { facStep: $facStep, offStep: $offStep, fac: " . js(\@fac) . ", off: " . js(\@off) . " },\n";
print "  settings: { reduction: '" . ($red == 0 ? 'retard' : 'cut') . "', reductionRaw: $red, dtcMode: " .
      "{ Rain: $dtc[0], Int: $dtc[1], Dry1: $dtc[2], Dry2: $dtc[3] } },\n";
print "};\n";
