#!/usr/bin/perl
# Fill duplicated slip target maps of the current dataset with maps from another dataset.
#   perl tools/fill-duplicate-maps.pl js/dataset.js other-dataset.js > merged.js
# (both inputs are generated by tools/bmwrc25-to-js.pl)
#
# - Maps with identical content count as duplicates. Per group, maps used by the allocation
#   are kept; if none is used, the lowest map id is kept. The rest are free slots.
# - Maps of the other dataset that do not exist yet (by content, de-duplicated) fill the free
#   slots: into the same map number when that slot is free, otherwise the lowest free slot.
# - Allocation, user offset / factor and settings stay those of the current dataset.
use strict;
use warnings;

my ($curFile, $srcFile) = @ARGV;
die "usage: $0 current.js other.js\n" unless $srcFile;

sub slurp { open my $h, '<', $_[0] or die "$_[0]: $!\n"; local $/; return scalar <$h> }
sub targets {
  my $s = shift; my %t;
  while ($s =~ /\{ id: (\d+), (lean: \[[^\]]*\], rows: \[.*?\]\])(?:, from: "[^"]*")? \}/g) { $t{$1} = $2 }
  return \%t;
}
my $cur = slurp($curFile);
my $src = slurp($srcFile);
my $ct = targets($cur);
my $st = targets($src);
my ($srcName) = $src =~ /source: "((?:[^"\\]|\\.)*)"/;
my ($alloc) = $cur =~ /allocation: \{([^}]*)\}/;
my %used = map { $_ => 1 } map { /(\d+)/g } ($alloc =~ /\[([^\]]*)\]/g);   # ids inside [ ] only (not "Dry1")

# free slots: duplicates in the current dataset
my (%group, @free, %content);
push @{ $group{ $ct->{$_} } }, $_ for sort { $a <=> $b } keys %$ct;
for my $ids (values %group) {
  my @keep = grep { $used{$_} } @$ids;
  @keep = ($ids->[0]) unless @keep;
  my %k = map { $_ => 1 } @keep;
  push @free, grep { !$k{$_} } @$ids;
  $content{ $ct->{$_} } = 1 for @keep;
}
@free = sort { $a <=> $b } @free;

# candidates: maps of the other dataset that are not there yet
my @cand;
for my $id (sort { $a <=> $b } keys %$st) {
  next if $content{ $st->{$id} }++;
  push @cand, $id;
}

# same number first, then the lowest free slot
my (%fill, %freeSet);
$freeSet{$_} = 1 for @free;
for my $id (@cand) { if ($freeSet{$id}) { $fill{$id} = $id; delete $freeSet{$id} } }
for my $id (@cand) {
  next if grep { $fill{$_} == $id } keys %fill;
  my ($slot) = sort { $a <=> $b } keys %freeSet;
  last unless defined $slot;
  $fill{$slot} = $id; delete $freeSet{$slot};
}

my @log;
for my $slot (sort { $a <=> $b } keys %fill) {
  my $id = $fill{$slot};
  my $repl = "{ id: $slot, $st->{$id}, from: \"$srcName · Map $id\" }";
  $cur =~ s/\{ id: $slot, lean: \[[^\]]*\], rows: \[.*?\]\](?:, from: "[^"]*")? \}/$repl/;
  push @log, "Map $slot <- $srcName Map $id";
}
my @left = sort { $a <=> $b } keys %freeSet;
push @log, 'still duplicated: Maps ' . join(', ', @left) if @left;
$cur =~ s/^(window\.MRCK_DATASET)/join('', map { "\/\/ $_\n" } @log) . $1/me;
print $cur;
print STDERR "$_\n" for @log;
